DROP TABLE IF EXISTS booking CASCADE;
DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS item_request CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name  VARCHAR(100)                                        NOT NULL,
    email VARCHAR(100)                                        NOT NULL,
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS item_request
(
    id           BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    description  VARCHAR(255),
    requestor_id BIGINT REFERENCES users (id) ON DELETE CASCADE,
    created      TIMESTAMP
);

CREATE TABLE IF NOT EXISTS items
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name         VARCHAR(200)                                        NOT NULL,
    description  VARCHAR(1000)                                       NOT NULL,
    is_available BOOLEAN                                             NOT NULL,
    owner_id     BIGINT REFERENCES users (id) ON DELETE CASCADE,
    request_id   BIGINT REFERENCES item_request (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS booking
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    start          TIMESTAMP,
    end_booking    TIMESTAMP,
    item_id        BIGINT REFERENCES items (id) ON DELETE CASCADE,
    booker_user_id BIGINT REFERENCES users (id) ON DELETE CASCADE,
    status         VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS comments
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    text      VARCHAR(1000)                                       NOT NULL,
    item_id   BIGINT REFERENCES items (id) ON DELETE CASCADE,
    author_id BIGINT REFERENCES items (id) ON DELETE CASCADE,
    created   TIMESTAMP WITHOUT TIME ZONE                         NOT NULL
)